export const initialState = {
  products: {
    data: [
      {
        _id: '1',
        title: 'American Gods',
        author: 'Neil Gaiman',
        cover: '/images/authors/gaiman/books/american-gods/1.jpg',
        price: 14.99,
        description: 'American Gods (2001) is a fantasy novel by British author Neil Gaiman. The novel is a blend of Americana, fantasy, and various strands of ancient and modern mythology, all centering on the mysterious and taciturn Shadow. The book was published in 2001 by Headline in the United Kingdom and by William Morrow in the United States. It gained a positive critical response and won the Hugo and Nebula awards in 2002. A special tenth anniversary edition, which includes the "author\'s preferred text" and 12,000 additional words, was published in June 2011 by William Morrow. Two audio versions of the book were produced and published by Harper Audio: an unabridged version of the original published edition, read by George Guidall, released in 2001; a full cast audiobook version of the tenth anniversary edition, released in 2011. In March 2017, The Folio Society published a special collector\'s edition of American Gods, with many corrections to the author\'s preferred text version. In April 2017, Starz began airing a television adaptation of the novel. Bryan Fuller and Michael Green served as showrunners, and Gaiman is an executive producer. Fuller and Green departed the show after the first season.',
        photos: [
          '/images/authors/gaiman/gaiman.jpg',
          '/images/authors/gaiman/books/american-gods/2.jpg',
          '/images/authors/gaiman/books/american-gods/3.jpg',
        ],
      },
      {
        _id: '2',
        title: 'Anansi Boys',
        author: 'Neil Gaiman',
        cover: '/images/authors/gaiman/books/anansi-boys/1.jpg',
        price: 13.99,
        description: 'Anansi Boys is a fantasy novel by English writer Neil Gaiman. In the novel, "Mr. Nancy" — an incarnation of the West African trickster god Anansi — dies, leaving twin sons, who in turn discover one another\'s existence after being separated as young children. The novel follows their adventures as they explore their common heritage. Although it is not a sequel to Gaiman\'s previous novel American Gods, the character of Mr. Nancy appears in both books. Gaiman mentioned author Thorne Smith as a strong influence when writing the book; "In the back of my head, when I was writing it, I had a writer named Thorne Smith", and "...the Thorne Smith approach to books with eruptions of magic into normal lives seemed like a territory that would be worthwhile to explore." In the dedication to the novel, he also "tips his hat" to P. G. Wodehouse, Tex Avery and Zora Neale Hurston. Anansi Boys was published on 20 September 2005 and was released in paperback on 1 October 2006. The book debuted at number one on The New York Times Best Seller list, and won both the Locus Award and the British Fantasy Society Award in 2006. The audiobook was released in 2005, narrated by Lenny Henry.',
        photos: [
          '/images/authors/gaiman/gaiman.jpg',
          '/images/authors/gaiman/books/anansi-boys/2.jpg',
          '/images/authors/gaiman/books/anansi-boys/3.jpg',
        ],
      },
      {
        _id: '3',
        title: 'Coraline',
        author: 'Neil Gaiman',
        cover: '/images/authors/gaiman/books/coraline/1.jpg',
        price: 9.99,
        description: 'Coraline is a dark fantasy children\'s novella by British author Neil Gaiman, published in 2002 by Bloomsbury and Harper Collins. It was awarded the 2003 Hugo Award for Best Novella, the 2003 Nebula Award for Best Novella, and the 2002 Bram Stoker Award for Best Work for Young Readers. The Guardian ranked Coraline #82 in its list of 100 Best Books of the 21st Century. Gaiman started writing Coraline in 1990. The titular character\'s name came from a typo in "Caroline". According to Gaiman, "I had typed the name Caroline, and it came out wrong. I looked at the word Coraline, and knew it was someone\'s name. I wanted to know what happened to her." It was adapted as a 2009 stop-motion animated film, directed by Henry Selick.',
        photos: [
          '/images/authors/gaiman/gaiman.jpg',
          '/images/authors/gaiman/books/coraline/2.jpg',
          '/images/authors/gaiman/books/coraline/3.jpg',
        ],
      },
      {
        _id: '4',
        title: 'Neverwhere',
        author: 'Neil Gaiman',
        cover: '/images/authors/gaiman/books/neverwhere/1.jpg',
        price: 11.99,
        description: 'Neverwhere is the companion novelisation written by English author Neil Gaiman of the television serial Neverwhere, by Gaiman and Lenny Henry. The plot and characters are exactly the same as in the series, with the exception that the novel form allowed Gaiman to expand and elaborate on certain elements of the story and restore changes made in the televised version from his original plans. Most notable is the appearance of the Floating Market at Harrods (in the novel) rather than under Battersea power station (the TV series). This is because the management of Harrods changed their minds about proposed filming. The novel was originally released by BBC Books in 1996, three episodes into the television series run. It was accompanied by a spoken word CD and cassette release, also by the BBC. The novel enjoyed great success, whereas its television roots did not receive as much international exposure as the novel. In addition to being translated into various languages, it was also re-published as an "Author\'s Preferred Text" version, (a combination of the international and original English version, with additional scenes re-inserted by Gaiman) alongside American Gods in 2006. The original BBC Books version had a cover by longtime Gaiman collaborator Dave McKean, taken from the bird\'s head rings, flaming fist and London Underground styled graphics created by McKean for the series, as well as a brief section by Gaiman on the making of the series.',
        photos: [
          '/images/authors/gaiman/gaiman.jpg',
          '/images/authors/gaiman/books/neverwhere/2.jpg',
          '/images/authors/gaiman/books/neverwhere/3.jpg',
        ],
      },
      {
        _id: '5',
        title: 'The Colour of Magic',
        author: 'Terry Pratchett',
        cover: '/images/authors/pratchett/books/the-colour-of-magic/1.jpg',
        price: 7.99,
        description: 'The Colour of Magic is a 1983 fantasy comedy novel by Terry Pratchett, and is the first book of the Discworld series. The first printing of the British edition consisted of only 506 copies. Pratchett has described it as "an attempt to do for the classical fantasy universe what Blazing Saddles did for Westerns." The story takes place on the Discworld, a planet-sized flat disc carried through space on the backs of four gargantuan elephants – Berilia, Tubul, Great T\'Phon and Jerakeen – who themselves stand on the shell of Great A\'Tuin, a gigantic star turtle. The surface of the disc contains oceans and continents, and with them, civilizations, cities, forests and mountains.',
        photos: [
          '/images/authors/pratchett/pratchett.jpg',
          '/images/authors/pratchett/books/the-colour-of-magic/2.jpg',
          '/images/authors/pratchett/books/the-colour-of-magic/3.jpg',
        ],
      },
      {
        _id: '6',
        title: 'The Shepherd\'s Crown',
        author: 'Terry Pratchett',
        cover: '/images/authors/pratchett/books/the-shepherds-crown/1.jpg',
        price: 8.99,
        description: 'The Shepherd\'s Crown is a comic fantasy novel, the last book written by Terry Pratchett before his death in March 2015. It is the 41st novel in the Discworld series, and the fifth based on the character Tiffany Aching. It was published in the United Kingdom on 27 August 2015 by Penguin Random House publishers, and in the United States on 1 September 2015. In early June 2015, Pratchett\'s daughter Rhianna Pratchett announced that The Shepherd\'s Crown would be the last Discworld novel, and that no further work, including unfinished work, would be published.',
        photos: [
          '/images/authors/pratchett/pratchett.jpg',
          '/images/authors/pratchett/books/the-shepherds-crown/2.jpg',
          '/images/authors/pratchett/books/the-shepherds-crown/3.jpg',
        ],
      },
      {
        _id: '7',
        title: 'Snuff',
        author: 'Terry Pratchett',
        cover: '/images/authors/pratchett/books/snuff/1.jpg',
        price: 8.49,
        description: 'Snuff is the 39th novel in the Discworld series, written by Terry Pratchett. It was published on 11 October 2011 in the United States, and 13 October 2011 in the United Kingdom. The book is the third-fastest-selling novel in the United Kingdom since records began, having sold over 55,000 copies in the first three days. The book is the eighth City Watch story and is based largely around Commander Sir Sam Vimes. Pratchett emphasised that the word "snuff" has "at least two meanings". Commander Sam Vimes is forced by his wife, Lady Sybil, to take a holiday with their son, Young Sam, at her family\'s mansion Crundells. After a short time of enjoying his holiday, he discovers that the rural community has a dark past with the resident goblins, humanoid lifeforms that live in caves nearby. Vimes finds out that the son of Lord Rust has been enslaving goblins to force them to work on his tobacco plantations in Howondaland, allowing him to manufacture cigars cheaply that are then smuggled to Ankh-Morpork. After teaming up with the local constable, a young man called Upshot, Vimes manages to arrest those responsible for the crime. In the end, thanks to his wife\'s organisational skills and powers of persuasion, goblins are recognised as citizens by all major nations and rulers. Rust\'s son is disinherited and exiled to Fourecks, where Lord Vetinari assures an eye will be kept on him.',
        photos: [
          '/images/authors/pratchett/pratchett.jpg',
          '/images/authors/pratchett/books/snuff/2.jpg',
          '/images/authors/pratchett/books/snuff/3.jpg',
        ],
      },
      {
        _id: '8',
        title: 'Guards! Guards!',
        author: 'Terry Pratchett',
        cover: '/images/authors/pratchett/books/guards-guards/1.jpg',
        price: 7.99,
        description: 'Guards! Guards! is a fantasy novel by British writer Terry Pratchett, the eighth in the Discworld series, first published in 1989. It is the first novel about the Ankh-Morpork City Watch. The first Discworld computer game borrowed heavily from Guards! Guards! in terms of plot. The story follows a plot by a secret brotherhood, the Unique and Supreme Lodge of the Elucidated Brethren of the Ebon Night, to overthrow the Patrician of Ankh-Morpork and install a puppet king, under the control of the Supreme Grand Master. Using a stolen magic book, they summon a dragon to strike fear into the people of Ankh-Morpork. Once a suitable state of terror and panic has been created, the Supreme Grand Master proposes to put forth an "heir" to the throne, who will slay the dragon and rid the city of tyranny. It is the task of the Night Watch – Captain Vimes, Sergeant Colon, Corporal Nobbs, and new volunteer Carrot Ironfoundersson – to stop them, with some help from the Librarian of the Unseen University, an orangutan trying to get the stolen book back.',
        photos: [
          '/images/authors/pratchett/pratchett.jpg',
          '/images/authors/pratchett/books/guards-guards/2.jpg',
          '/images/authors/pratchett/books/guards-guards/3.jpg',
        ],
      },
      {
        _id: '9',
        title: 'The Amazing Maurice and His Educated Rodents',
        author: 'Terry Pratchett',
        cover: '/images/authors/pratchett/books/the-amazing-maurice-and-his-educated-rodents/1.jpg',
        price: 5.99,
        description: 'The Amazing Maurice and His Educated Rodents is a children\'s fantasy novel by British writer Terry Pratchett, published by Doubleday in 2001. It is the 28th novel in the Discworld series and the first written for children. The story is a new take on the German fairy tale about the Pied Piper of Hamelin and a parody of the folk tale genre. Pratchett won the annual Carnegie Medal from the British librarians, recognising the year\'s best children\'s book published in the U.K. It was his first major award.',
        photos: [
          '/images/authors/pratchett/pratchett.jpg',
          '/images/authors/pratchett/books/the-amazing-maurice-and-his-educated-rodents/2.jpg',
          '/images/authors/pratchett/books/the-amazing-maurice-and-his-educated-rodents/3.jpg',
        ],
      },
      {
        _id: '10',
        title: 'Harry Potter and the Prisoner of Azkaban',
        author: 'Joanne Kathleen Rowling',
        cover: '/images/authors/rowling/books/harry-potter-and-the-prisoner-of-azkaban/1.jpg',
        price: 10.99,
        description: 'Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and is the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort\'s old allies. The book was published in the United Kingdom on 8 July 1999 by Bloomsbury and in the United States on 8 September 1999 by Scholastic, Inc. Rowling found the book easy to write, finishing it just a year after she began writing it. The book sold 68,000 copies in just three days after its release in the United Kingdom and since has sold over three million in the country. The book won the 1999 Whitbread Children\'s Book Award, the Bram Stoker Award, and the 2000 Locus Award for Best Fantasy Novel and was short-listed for other awards, including the Hugo. The film adaptation of the novel was released in 2004, grossing more than $796 million and earning critical acclaim. Video games loosely based on Harry Potter and the Prisoner of Azkaban were also released for several platforms, and most obtained favourable reviews.',
        photos: [
          '/images/authors/rowling/rowling.jpeg',
          '/images/authors/rowling/books/harry-potter-and-the-prisoner-of-azkaban/2.jpg',
          '/images/authors/rowling/books/harry-potter-and-the-prisoner-of-azkaban/3.jpg',
        ],
      },
      {
        _id: '11',
        title: 'Harry Potter and the Half-Blood Prince',
        author: 'Joanne Kathleen Rowling',
        cover: '/images/authors/rowling/books/harry-potter-and-the-half-blood-prince/1.jpg',
        price: 12.99,
        description: 'Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J.K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter\'s sixth year at Hogwarts, the novel explores the past of the boy wizard\'s nemesis, Lord Voldemort, and Harry\'s preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore. The book was published in the United Kingdom by Bloomsbury and in the United States by Scholastic on 16 July 2005, as well as in several other countries. It sold nine million copies in the first 24 hours after its release, a record that was eventually broken by its sequel, Harry Potter and the Deathly Hallows. There were many controversies before and after it was published, including the right to read copies delivered before the release date in Canada. Reception to the novel was generally positive, and it won several awards and honours, including the 2006 British Book of the Year award. Reviewers noted that the book took on a darker tone than its predecessors, though it did contain some humour. Some considered the main themes to be love, death, trust, and redemption. The considerable character development of Harry and many other teenage characters also drew attention. The film adaptation of Harry Potter and the Half-Blood Prince was released 15 July 2009 by Warner Bros.',
        photos: [
          '/images/authors/rowling/rowling.jpeg',
          '/images/authors/rowling/books/harry-potter-and-the-half-blood-prince/2.jpg',
          '/images/authors/rowling/books/harry-potter-and-the-half-blood-prince/3.jpg',
        ],
      },
      {
        _id: '12',
        title: 'Harry Potter and the Deathly Hallows',
        author: 'Joanne Kathleen Rowling',
        cover: '/images/authors/rowling/books/harry-potter-and-the-deathly-hallows/1.jpg',
        price: 14.49,
        description: 'Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. It was released on 21 July 2007 in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort. Deathly Hallows shattered sales records upon release, surpassing marks set by previous titles of the Harry Potter series. It holds the Guinness World Record for most novels sold within 24 hours of release, with 8.3 million sold in the US and 2.65 million in the UK. Generally well received by critics, the book won the 2008 Colorado Blue Spruce Book Award, and the American Library Association named it the "Best Book for Young Adults". A film adaptation of the novel was released in two parts: Harry Potter and the Deathly Hallows – Part 1 in November 2010 and Part 2 in July 2011.',
        photos: [
          '/images/authors/rowling/rowling.jpeg',
          '/images/authors/rowling/books/harry-potter-and-the-deathly-hallows/2.jpg',
          '/images/authors/rowling/books/harry-potter-and-the-deathly-hallows/3.jpg',
        ],
      },
      {
        _id: '13',
        title: 'The Fellowship of the Ring',
        author: 'John Ronald Reuel Tolkien',
        cover: '/images/authors/tolkien/books/the-fellowship-of-the-ring/1.jpg',
        price: 11.99,
        description: 'The Fellowship of the Ring is the first of three volumes of the epic novel The Lord of the Rings by the English author J. R. R. Tolkien. It is followed by The Two Towers and The Return of the King. It takes place in the fictional universe of Middle-earth. It was originally published on 29 July 1954 in the United Kingdom. The volume consists of a foreword, in which the author discusses his writing of The Lord of the Rings, a prologue titled "Concerning Hobbits, and other matters", and the main narrative in Book I and Book II. Tolkien envisioned The Lord of the Rings as a single volume work divided into six sections he called "books" along with extensive appendices. The original publisher decided to split the work into three parts. It was also the publisher\'s decision to place the fifth and sixth books and the appendices into one volume under the title The Return of the King, about Aragorn\'s assumption of the throne of Gondor. Tolkien indicated he would have preferred The War of the Ring as a title, as it gave away less of the story. Before the decision to publish The Lord of the Rings in three volumes was made, Tolkien had hoped to publish the novel in one volume, possibly also combined with The Silmarillion. However, he had proposed titles for the individual six sections. Of the two books that comprise what became The Fellowship of the Ring the first was to be called The First Journey or The Ring Sets Out. The name of the second was The Journey of the Nine Companions or The Ring Goes South. The titles The Ring Sets Out and The Ring Goes South were used in the Millennium edition.',
        photos: [
          '/images/authors/tolkien/tolkien.jpg',
          '/images/authors/tolkien/books/the-fellowship-of-the-ring/2.jpg',
          '/images/authors/tolkien/books/the-fellowship-of-the-ring/3.jpg',
        ],
      },
      {
        _id: '14',
        title: 'The Two Towers',
        author: 'John Ronald Reuel Tolkien',
        cover: '/images/authors/tolkien/books/the-two-towers/1.jpg',
        price: 11.99,
        description: 'The Two Towers is the second volume of J. R. R. Tolkien\'s high fantasy novel The Lord of the Rings. It is preceded by The Fellowship of the Ring and followed by The Return of the King. The Lord of the Rings is composed of six "books", aside from an introduction, a prologue and six appendices. However, the novel was originally published as three separate volumes, due to post-World War II paper shortages and size and price considerations. The Two Towers covers Books III and IV. Tolkien wrote: "The Two Towers gets as near as possible to finding a title to cover the widely divergent Books 3 and 4; and can be left ambiguous." At this stage he planned to title the individual books. The proposed title for Book III was The Treason of Isengard. Book IV was titled The Journey of the Ringbearers or The Ring Goes East. The titles The Treason of Isengard and The Ring Goes East were used in the Millennium edition. In letters to Rayner Unwin, Tolkien considered naming the two as Orthanc and Barad-dûr, Minas Tirith and Barad-dûr, or Orthanc and the Tower of Cirith Ungol. However, a month later, he wrote a note published at the end of The Fellowship of the Ring, and later drew a cover illustration, both of which identified the pair as Minas Morgul and Orthanc. In the illustration, Orthanc is shown as a black tower, three-horned, with the sign of the White Hand beside it; Minas Morgul is a white tower, with a thin waning moon above it, in reference to its original name, Minas Ithil, the Tower of the Rising Moon. Between the two towers a Nazgûl flies.',
        photos: [
          '/images/authors/tolkien/tolkien.jpg',
          '/images/authors/tolkien/books/the-two-towers/2.jpg',
          '/images/authors/tolkien/books/the-two-towers/3.jpg',
        ],
      },
      {
        _id: '15',
        title: 'The Return of the King',
        author: 'John Ronald Reuel Tolkien',
        cover: '/images/authors/tolkien/books/the-return-of-the-king/1.jpg',
        price: 11.99,
        description: 'The Return of the King is the third and final volume of J. R. R. Tolkien\'s The Lord of the Rings, following The Fellowship of the Ring and The Two Towers. It was published in 1955. The story begins in the kingdom of Gondor, which is soon to be attacked by the Dark Lord Sauron. Tolkien conceived of The Lord of the Rings as a single work comprising six "books" plus extensive appendices. The original publisher split the work into three volumes, publishing the fifth and sixth books with the appendices into the final volume with the title The Return of the King. Tolkien felt the chosen title revealed too much of the story, and indicated he preferred The War of the Ring as a title. The proposed title for Book V was The War of the Ring. Book VI was to be The End of the Third Age. These titles were used in the Millennium edition. The Return of the King was in the end published as the third and final volume of The Lord of the Rings, on 20 October 1955 in the UK.',
        photos: [
          '/images/authors/tolkien/tolkien.jpg',
          '/images/authors/tolkien/books/the-return-of-the-king/2.jpg',
          '/images/authors/tolkien/books/the-return-of-the-king/3.jpg',
        ],
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  cart: {
    data: [
      {
        _id: '4',
        title: 'Neverwhere',
        cover: '/images/authors/gaiman/books/neverwhere/1.jpg',
        price: 11.99,
        amount: 1,
      },
      {
        _id: '9',
        title: 'The Amazing Maurice and His Educated Rodents',
        cover: '/images/authors/pratchett/books/the-amazing-maurice-and-his-educated-rodents/1.jpg',
        price: 5.99,
        amount: 3,
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
